In [4]:
import numpy as np

arr1 = np.array([[1,2.5,3],[4,5,6.7]])

print(arr1)

[[1.  2.5 3. ]
 [4.  5.  6.7]]


In [18]:
arr1.ndim #fund the array dimension --> 2

2

In [20]:
arr1.dtype

dtype('float64')

In [19]:
arr1.size

6

In [21]:
arr1.shape

(2, 3)

In [30]:
arr1.reshape(3,2)

array([[1. , 2.5],
       [3. , 4. ],
       [5. , 6.7]])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
arr1.ravel() # it make multidimension to one-dimension

array([1. , 2.5, 3. , 4. , 5. , 6.7])

In [33]:
arr1.max()

6.7

In [34]:
arr1.min()

1.0

In [35]:
arr1.sum()

22.2

In [38]:
arr1.sum(axis=0)

array([5. , 7.5, 9.7])

In [39]:
arr1.sum(axis=1)

array([ 6.5, 15.7])

In [5]:
arr3=np.array([[1,2],[4,9]])
arr4=np.array([[1,5],[5,9]])
np.sqrt(arr3)

array([[1.        , 1.41421356],
       [2.        , 3.        ]])

In [43]:
arr3.std() #standard daviation

3.082207001484488

In [44]:
np.std(arr3)

3.082207001484488

In [48]:
arr3+arr4

array([[ 2,  7],
       [ 9, 18]])

In [6]:
arr3-arr4

array([[ 0, -3],
       [-1,  0]])

In [49]:
arr3*arr4

array([[ 1, 10],
       [20, 81]])

In [50]:
arr3/arr4

array([[1. , 0.4],
       [0.8, 1. ]])

In [51]:
arr3.dot(arr4)

array([[ 11,  23],
       [ 49, 101]])

In [ ]:
# list slicing

In [54]:
n = [6,7,8]

In [55]:
n[0:2]

[6, 7]

In [57]:
new_arr=np.array([6,7,8])

In [58]:
new_arr[0:2]

array([6, 7])

In [59]:
new_arr[-1]

8

In [63]:
a = np.array([[6,7,8],[1,2,3],[7,2,3]])

In [64]:
a[1,2]

3

In [65]:
a[0:2,2]

array([8, 3])

In [66]:
a[-1]

array([7, 2, 3])

In [67]:
a[-1,0:2]

array([7, 2])

In [68]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [2, 3]])

In [73]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [75]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
x=np.arange(6).reshape(2,3)
y=np.arange(6,12).reshape(2,3)

In [82]:
np.vstack((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
np.hstack((x,y))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [116]:
z=np.arange(12).reshape(2,6)
np.hsplit(z,3)
np.vsplit(z,2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]